version: '3'

services:
  web1:
    build: ./myapp1
    container_name: web1
  web2:
    build: ./myapp2
    container_name: web2
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
